import os


class Config:
    # Fyers API Configuration
    CLIENT_ID = "LXM1CM3V32-100"
    SECRET_KEY = "DN4NU7JVCQ"
    REDIRECT_URI = os.environ.get("FYERS_REDIRECT_URI", "https://www.google.com/")

    # Fyers API Configuration for Historical Data (365 days)
    FYERS_HIST_DATA_APP_ID = os.environ.get("FYERS_HIST_DATA_APP_ID", "").strip()
    HIST_CLIENT_ID = "LXM1CM3V32-100"
    HIST_SECRET_KEY = "DN4NU7JVCQ"
    HIST_REDIRECT_URI = os.environ.get("FYERS_HIST_REDIRECT_URI", "https://www.google.com/")

    # Flask Configuration
    SECRET_KEY_FLASK = os.environ.get("SESSION_SECRET", "your-secret-key-here")

    # F&O Stocks symbols for WebSocket subscription (alphabetically arranged for uniform display)
    FNO_STOCKS = [
        "NSE:ABCAPITAL-EQ", "NSE:ADANIENSOL-EQ", "NSE:ADANIENT-EQ",
        "NSE:ADANIGREEN-EQ", "NSE:ADANIPORTS-EQ", "NSE:ALKEM-EQ",
        "NSE:AMBER-EQ", "NSE:AMBUJACEM-EQ", "NSE:ANGELONE-EQ",
        "NSE:APOLLOHOSP-EQ", "NSE:ASHOKLEY-EQ", "NSE:ASIANPAINT-EQ",
        "NSE:ASTRAL-EQ", "NSE:AUBANK-EQ", "NSE:AUROPHARMA-EQ",
        "NSE:AXISBANK-EQ", "NSE:BAJAJ-AUTO-EQ", "NSE:BAJAJFINSV-EQ",
        "NSE:BAJFINANCE-EQ", "NSE:BANDHANBNK-EQ", "NSE:BANKBARODA-EQ",
        "NSE:BANKINDIA-EQ", "NSE:BDL-EQ", "NSE:BEL-EQ",
        "NSE:BHARATFORG-EQ", "NSE:BHARTIARTL-EQ", "NSE:BHEL-EQ",
        "NSE:BIOCON-EQ", "NSE:BLUESTARCO-EQ", "NSE:BOSCHLTD-EQ",
        "NSE:BPCL-EQ", "NSE:BRITANNIA-EQ", "NSE:BSE-EQ",
        "NSE:CAMS-EQ", "NSE:CANBK-EQ", "NSE:CDSL-EQ",
        "NSE:CGPOWER-EQ", "NSE:CHOLAFIN-EQ", "NSE:CIPLA-EQ",
        "NSE:COALINDIA-EQ", "NSE:COFORGE-EQ", "NSE:COLPAL-EQ",
        "NSE:CONCOR-EQ", "NSE:CROMPTON-EQ", "NSE:CUMMINSIND-EQ",
        "NSE:CYIENT-EQ", "NSE:DABUR-EQ", "NSE:DALBHARAT-EQ",
        "NSE:DELHIVERY-EQ", "NSE:DLF-EQ", "NSE:DMART-EQ",
        "NSE:DIVISLAB-EQ", "NSE:DIXON-EQ", "NSE:DRREDDY-EQ",
        "NSE:EICHERMOT-EQ", "NSE:ETERNAL-EQ", "NSE:EXIDEIND-EQ",
        "NSE:FEDERALBNK-EQ", "NSE:FORTIS-EQ", "NSE:GAIL-EQ",
        "NSE:GLENMARK-EQ", "NSE:GMRAIRPORT-EQ", "NSE:GODREJCP-EQ",
        "NSE:GODREJPROP-EQ", "NSE:GRASIM-EQ", "NSE:HAL-EQ",
        "NSE:HAVELLS-EQ", "NSE:HCLTECH-EQ", "NSE:HDFCAMC-EQ",
        "NSE:HDFCBANK-EQ", "NSE:HDFCLIFE-EQ", "NSE:HEROMOTOCO-EQ",
        "NSE:HFCL-EQ", "NSE:HINDALCO-EQ", "NSE:HINDPETRO-EQ",
        "NSE:HINDUNILVR-EQ", "NSE:HINDZINC-EQ", "NSE:HUDCO-EQ",
        "NSE:ICICIBANK-EQ", "NSE:ICICIGI-EQ", "NSE:ICICIPRULI-EQ",
        "NSE:IDEA-EQ", "NSE:IDFCFIRSTB-EQ", "NSE:IEX-EQ",
        "NSE:IGL-EQ", "NSE:IIFL-EQ", "NSE:INDIANB-EQ",
        "NSE:INDHOTEL-EQ", "NSE:INDIGO-EQ", "NSE:INDUSTOWER-EQ",
        "NSE:INDUSINDBK-EQ", "NSE:INFY-EQ", "NSE:INOXWIND-EQ",
        "NSE:IOC-EQ", "NSE:IRCTC-EQ", "NSE:IREDA-EQ",
        "NSE:IRFC-EQ", "NSE:ITC-EQ", "NSE:JINDALSTEL-EQ",
        "NSE:JIOFIN-EQ", "NSE:JSWENERGY-EQ", "NSE:JSWSTEEL-EQ",
        "NSE:JUBLFOOD-EQ", "NSE:KALYANKJIL-EQ", "NSE:KAYNES-EQ",
        "NSE:KEI-EQ", "NSE:KFINTECH-EQ", "NSE:KOTAKBANK-EQ",
        "NSE:KPITTECH-EQ", "NSE:LAURUSLABS-EQ", "NSE:LICHSGFIN-EQ",
        "NSE:LICI-EQ", "NSE:LODHA-EQ", "NSE:LT-EQ",
        "NSE:LTF-EQ", "NSE:LTIM-EQ", "NSE:LUPIN-EQ",
        "NSE:M&M-EQ", "NSE:MANAPPURAM-EQ", "NSE:MANKIND-EQ",
        "NSE:MARICO-EQ", "NSE:MARUTI-EQ", "NSE:MAXHEALTH-EQ",
        "NSE:MAZDOCK-EQ", "NSE:MCX-EQ", "NSE:MFSL-EQ",
        "NSE:MOTHERSON-EQ", "NSE:MPHASIS-EQ", "NSE:MUTHOOTFIN-EQ",
        "NSE:NATIONALUM-EQ", "NSE:NAUKRI-EQ", "NSE:NBCC-EQ",
        "NSE:NCC-EQ", "NSE:NESTLEIND-EQ", "NSE:NHPC-EQ",
        "NSE:NMDC-EQ", "NSE:NTPC-EQ", "NSE:NUVAMA-EQ",
        "NSE:NYKAA-EQ", "NSE:OBEROIRLTY-EQ", "NSE:OFSS-EQ",
        "NSE:OIL-EQ", "NSE:ONGC-EQ", "NSE:PAGEIND-EQ",
        "NSE:PATANJALI-EQ", "NSE:PAYTM-EQ", "NSE:PERSISTENT-EQ",
        "NSE:PETRONET-EQ", "NSE:PFC-EQ", "NSE:PGEL-EQ",
        "NSE:PHOENIXLTD-EQ", "NSE:PIDILITIND-EQ", "NSE:PIIND-EQ",
        "NSE:PNB-EQ", "NSE:PNBHOUSING-EQ", "NSE:POLICYBZR-EQ",
        "NSE:POLYCAB-EQ", "NSE:POWERGRID-EQ", "NSE:PPLPHARMA-EQ",
        "NSE:PRESTIGE-EQ", "NSE:RBLBANK-EQ", "NSE:RECLTD-EQ",
        "NSE:RELIANCE-EQ", "NSE:RVNL-EQ", "NSE:SAIL-EQ",
        "NSE:SAMMAANCAP-EQ", "NSE:SBICARD-EQ", "NSE:SBILIFE-EQ",
        "NSE:SBIN-EQ", "NSE:SHREECEM-EQ", "NSE:SHRIRAMFIN-EQ",
        "NSE:SIEMENS-EQ", "NSE:SOLARINDS-EQ", "NSE:SONACOMS-EQ",
        "NSE:SRF-EQ", "NSE:SUNPHARMA-EQ", "NSE:SUPREMEIND-EQ",
        "NSE:SUZLON-EQ", "NSE:SYNGENE-EQ", "NSE:TATACHEM-EQ",
        "NSE:TATACONSUM-EQ", "NSE:TATAELXSI-EQ", "NSE:TATAMOTORS-EQ",
        "NSE:TATAPOWER-EQ", "NSE:TATASTEEL-EQ", "NSE:TATATECH-EQ",
        "NSE:TCS-EQ", "NSE:TECHM-EQ", "NSE:TIINDIA-EQ",
        "NSE:TITAN-EQ", "NSE:TITAGARH-EQ", "NSE:TORNTPHARM-EQ",
        "NSE:TORNTPOWER-EQ", "NSE:TRENT-EQ", "NSE:TVSMOTOR-EQ",
        "NSE:ULTRACEMCO-EQ", "NSE:UNIONBANK-EQ", "NSE:UNITDSPR-EQ",
        "NSE:UNOMINDA-EQ", "NSE:UPL-EQ", "NSE:VBL-EQ",
        "NSE:VEDL-EQ", "NSE:VOLTAS-EQ", "NSE:WIPRO-EQ",
        "NSE:YESBANK-EQ", "NSE:ZYDUSLIFE-EQ"
    ]

    # INDEX symbols for top floating bar (invalid symbols removed)
    INDEX_SYMBOLS = [
        "NSE:NIFTY50-INDEX",
        "BSE:SENSEX-INDEX",  # Added as 2nd card, next to Nifty 50
        "NSE:NIFTYBANK-INDEX",
        "NSE:NIFTYIT-INDEX",
        "NSE:FINNIFTY-INDEX",
        "NSE:MIDCPNIFTY-INDEX",  # MIDCAP SELECT
        "NSE:NIFTYNXT50-INDEX",  # NIFTY NEXT 50
        "NSE:NIFTYFMCG-INDEX",
        "NSE:NIFTYPHARMA-INDEX",
        "NSE:NIFTYAUTO-INDEX",
        "NSE:NIFTYMETAL-INDEX",
        "NSE:NIFTYREALTY-INDEX",
        "NSE:NIFTYPSE-INDEX",
        "NSE:NIFTYPVTBANK-INDEX",
        "NSE:NIFTYMEDIA-INDEX",
        "NSE:NIFTYINFRA-INDEX",
        "NSE:NIFTYENERGY-INDEX",
        "NSE:NIFTYCOMMODITIES-INDEX",
        "NSE:NIFTYCPSE-INDEX",
        "NSE:NIFTYMIDCAP50-INDEX",
        "NSE:NIFTYSMLCAP100-INDEX", "NSE:INDIAVIX-INDEX"
    ]

    # Symbols that are problematic with Fyers API (to be excluded from bulk operations)
    EXCLUDED_SYMBOLS = [
        "NSE:NIFTYPHARMA-INDEX",
        "NSE:NIFTYAUTO-INDEX", 
        "NSE:NIFTYMETAL-INDEX",
        "NSE:NIFTYREALTY-INDEX",
        "NSE:NIFTYPSE-INDEX",
        "NSE:NIFTYPVTBANK-INDEX",
        "NSE:NIFTYMEDIA-INDEX",
        "NSE:NIFTYINFRA-INDEX",
        "NSE:NIFTYENERGY-INDEX",
        "NSE:NIFTYCOMMODITIES-INDEX",
        "NSE:NIFTYCPSE-INDEX"
    ]

    # Combined symbols for WebSocket and technical analysis (INDEX first, then F&O stocks alphabetically)
    NIFTY50_SYMBOLS = INDEX_SYMBOLS + FNO_STOCKS